"""sync runs

Revision ID: 59f7d3b1fe2b
Revises: acfb5de1ee67
Create Date: 2026-08-27 21:35:43.597400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f7d3b1fe2b'
down_revision: Union[str, Sequence[str], None] = 'acfb5de1ee67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('customers_synced', sa.Integer(), nullable=False),
    sa.Column('invoices_synced', sa.Integer(), nullable=False),
    sa.Column('payments_synced', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_org_id'), 'sync_runs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_org_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    # ### end Alembic commands ###
