"""durable action decisions and audit log

Revision ID: 5fa45c376089
Revises: 8fa02c97d757
Create Date: 2026-08-27 20:13:07.691842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa45c376089'
down_revision: Union[str, Sequence[str], None] = '8fa02c97d757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_decisions',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('approval_state', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('org_id', 'invoice_id')
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'invoice_id', 'sequence', name='uq_audit_entry_sequence')
    )
    op.create_index(op.f('ix_audit_log_entries_invoice_id'), 'audit_log_entries', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_org_id'), 'audit_log_entries', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_org_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_invoice_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_table('action_decisions')
    # ### end Alembic commands ###
