"""add customer_id to payments

Revision ID: 8fa02c97d757
Revises: 97f78aeb7b01
Create Date: 2026-08-15 17:05:01.034732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa02c97d757'
down_revision: Union[str, Sequence[str], None] = '97f78aeb7b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_column('payments', 'customer_id')
    # ### end Alembic commands ###
