"""canonical data model

Revision ID: 97f78aeb7b01
Revises: 
Create Date: 2026-08-15 16:47:13.738265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f78aeb7b01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_financial_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('current_cash', sa.Numeric(), nullable=False),
    sa.Column('expected_inflows', sa.Numeric(), nullable=False),
    sa.Column('upcoming_expenses', sa.Numeric(), nullable=False),
    sa.Column('payroll', sa.Numeric(), nullable=False),
    sa.Column('supplier_payments', sa.Numeric(), nullable=False),
    sa.Column('cash_threshold', sa.Numeric(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_financial_state_org_id'), 'business_financial_state', ['org_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('average_delay_days', sa.Float(), nullable=True),
    sa.Column('relationship_duration_days', sa.Integer(), nullable=True),
    sa.Column('treds_status', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_org_id'), 'customers', ['org_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('invoice_amount', sa.Numeric(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('acceptance_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoices_org_id'), 'invoices', ['org_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('actual_payment_date', sa.Date(), nullable=True),
    sa.Column('days_delayed', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_org_id'), 'payments', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_org_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_org_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_customers_org_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_business_financial_state_org_id'), table_name='business_financial_state')
    op.drop_table('business_financial_state')
    # ### end Alembic commands ###
