/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/action-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Action Queue
         * @description The prioritized daily action queue (FR-009).
         */
        get: operations["action_queue_api_action_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{invoice_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Action
         * @description Approve a recommendation and generate what it produces (FR-010, FR-012, FR-013).
         *
         *     `actor` comes from the verified token, never from the request. FR-014 asks
         *     who decided; a caller-supplied name would let anyone sign the audit trail
         *     with somebody else's identity, which is the one thing that record exists to
         *     prevent.
         */
        post: operations["approve_action_api_actions__invoice_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{invoice_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Action
         * @description Reject a recommendation. Invoice state is left unchanged (FR-010 AC-2).
         */
        post: operations["reject_action_api_actions__invoice_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cash Forecast
         * @description 30-day rolling cash forecast with shortfall contributors (FR-004, FR-015).
         */
        get: operations["cash_forecast_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoice/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investigation
         * @description Full investigation detail for one invoice (FR-003, FR-007, FR-014).
         */
        get: operations["investigation_api_invoice__invoice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoice/{invoice_id}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Artifact
         * @description Re-fetch the artifact an approved action produced (FR-011/012/013).
         *
         *     Without this, an approved dossier would exist only in the browser tab that
         *     approved it and vanish on reload — which is exactly the wrong property for a
         *     document someone intends to file.
         *
         *     Still gated: `build_artifact` raises `ApprovalRequired` for anything not
         *     approved, so this is a way to re-read a decision, not to bypass one.
         */
        get: operations["invoice_artifact_api_invoice__invoice_id__artifact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoice/{invoice_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Draft
         * @description Draft a reminder for one invoice (FR-011).
         *
         *     Not gated on approval — the draft is what the user reads in order to decide.
         *     Sending it is their own action in their own client (OQ-01).
         */
        get: operations["invoice_draft_api_invoice__invoice_id__draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Summary
         * @description Headline figures for the dashboard.
         */
        get: operations["portfolio_summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description The most recent sync for this org, successful or not.
         *
         *     Null when none has ever run. Without this, "the queue is empty" and "we
         *     have never managed to read the book" are indistinguishable from the
         *     outside, and the second is an outage reading as good news.
         */
        get: operations["sync_status_api_sync_get"];
        put?: never;
        /**
         * Run Sync
         * @description Pull this org's book from the configured connector into the canonical
         *     store (FR-001, on-demand half).
         *
         *     Returns 200 with `status: "FAILED"` rather than a 5xx when the connector is
         *     unreachable. The request itself succeeded — the sync is what failed, and
         *     that outcome is a recorded fact the caller needs to read, not an error to
         *     be swallowed by a generic handler. The previous portfolio is untouched
         *     (AC-2).
         */
        post: operations["run_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for an access token carrying the org.
         *
         *     One message for both "no such user" and "wrong password": distinguishing
         *     them tells an attacker which emails are registered.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the current token says you are. Used by the frontend to gate screens.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionQueueItemOut */
        ActionQueueItemOut: {
            /** Approvalstate */
            approvalState: string;
            /** Id */
            id: string;
            invoice: components["schemas"]["InvoiceOut"];
            prediction: components["schemas"]["DelayPredictionOut"];
            /** Priority */
            priority: string;
            /** Reason */
            reason: string;
            /** Recommendedaction */
            recommendedAction: string;
        };
        /** AgentFindingsOut */
        AgentFindingsOut: {
            /** Confidence */
            confidence: number;
            /** Disputedetected */
            disputeDetected: boolean;
            /** Evidence */
            evidence: string[];
            /** Paymentpromise */
            paymentPromise: boolean;
            /** Promiseddate */
            promisedDate: string | null;
        };
        /**
         * ApprovalResultOut
         * @description The outcome of a human decision, with whatever it produced (FR-010).
         */
        ApprovalResultOut: {
            /** Approvalstate */
            approvalState: string;
            artifact?: components["schemas"]["ArtifactOut"] | null;
            /** Audittrail */
            auditTrail: components["schemas"]["AuditEntryOut"][];
            /** Invoiceid */
            invoiceId: string;
            /** Recommendedaction */
            recommendedAction: string;
        };
        /**
         * ArtifactOut
         * @description A generated execution artifact (FR-011, FR-012, FR-013).
         *
         *     One shape for all three: the screen renders `contentMarkdown` and does not
         *     need to know whether it is holding a reminder, a financing submission, or a
         *     legal filing. `payload` carries the machine-readable TReDS body, which is
         *     the only one of the three that a downstream system would ever consume.
         */
        ArtifactOut: {
            /** Contentmarkdown */
            contentMarkdown: string;
            /**
             * Editable
             * @default false
             */
            editable: boolean;
            /** Kind */
            kind: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Title */
            title: string;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Decidedby */
            decidedBy: string;
            /** Timestamp */
            timestamp: string;
            /** What */
            what: string;
            /** Why */
            why: string;
        };
        /** CashForecastOut */
        CashForecastOut: {
            /** Cashthreshold */
            cashThreshold: number;
            /** Contributinginvoices */
            contributingInvoices: components["schemas"]["ContributingInvoiceOut"][];
            /** Points */
            points: components["schemas"]["ForecastPointOut"][];
            /** Shortfallamount */
            shortfallAmount: number | null;
            /** Shortfalldate */
            shortfallDate: string | null;
        };
        /** ContributingInvoiceOut */
        ContributingInvoiceOut: {
            /** Amount */
            amount: number;
            /** Contribution */
            contribution: number;
            /** Customername */
            customerName: string;
            /** Invoiceid */
            invoiceId: string;
        };
        /** DelayPredictionOut */
        DelayPredictionOut: {
            /** Bucket 0 15 */
            bucket_0_15: number;
            /** Bucket 16 30 */
            bucket_16_30: number;
            /** Bucket 31 45 */
            bucket_31_45: number;
            /** Bucket Over 45 */
            bucket_over_45: number;
        };
        /**
         * DraftChannel
         * @enum {string}
         */
        DraftChannel: "EMAIL" | "WHATSAPP";
        /** ForecastPointOut */
        ForecastPointOut: {
            /** Date */
            date: string;
            /** Projectedcash */
            projectedCash: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationOut */
        InvestigationOut: {
            /** Approvalstate */
            approvalState: string;
            /** Audittrail */
            auditTrail: components["schemas"]["AuditEntryOut"][];
            /** Factors */
            factors: components["schemas"]["PredictionFactorOut"][];
            findings: components["schemas"]["AgentFindingsOut"];
            invoice: components["schemas"]["InvoiceOut"];
            prediction: components["schemas"]["DelayPredictionOut"];
            /** Reason */
            reason: string;
            /** Recommendedaction */
            recommendedAction: string;
            rules: components["schemas"]["RuleFlagsOut"];
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Customerid */
            customerId: string;
            /** Customername */
            customerName: string;
            /** Daysoverdue */
            daysOverdue: number;
            /** Duedate */
            dueDate: string;
            /** Invoiceamount */
            invoiceAmount: number;
            /** Invoicedate */
            invoiceDate: string;
            /** Invoiceid */
            invoiceId: string;
            /** Paymentstatus */
            paymentStatus: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string;
            /** Org Id */
            org_id: string;
            /** User Id */
            user_id: string;
        };
        /** PortfolioSummaryOut */
        PortfolioSummaryOut: {
            /** Atrisk */
            atRisk: number;
            /** Openinvoices */
            openInvoices: number;
            /** Shortfallamount */
            shortfallAmount: number | null;
            /** Shortfalldate */
            shortfallDate: string | null;
            /** Totalreceivables */
            totalReceivables: number;
        };
        /** PredictionFactorOut */
        PredictionFactorOut: {
            /** Detail */
            detail: string;
            /** Direction */
            direction: string;
            /** Label */
            label: string;
        };
        /** RuleFlagsOut */
        RuleFlagsOut: {
            /** Statutoryflag */
            statutoryFlag: boolean;
            /** Statutoryinterest */
            statutoryInterest: number | null;
            /** Tredseligible */
            tredsEligible: boolean;
            /** Tredsineligiblereason */
            tredsIneligibleReason: string | null;
        };
        /**
         * SyncResultOut
         * @description One connector sync, successful or not (FR-001 AC-2).
         */
        SyncResultOut: {
            /**
             * Customerssynced
             * @default 0
             */
            customersSynced: number;
            /** Error */
            error?: string | null;
            /** Finishedat */
            finishedAt?: string | null;
            /**
             * Invoicessynced
             * @default 0
             */
            invoicesSynced: number;
            /**
             * Paymentssynced
             * @default 0
             */
            paymentsSynced: number;
            /** Source */
            source: string;
            /** Startedat */
            startedAt: string;
            /** Status */
            status: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Expires In */
            expires_in: number;
            /** Org Id */
            org_id: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    action_queue_api_action_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionQueueItemOut"][];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_action_api_actions__invoice_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResultOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_action_api_actions__invoice_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResultOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_forecast_api_forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashForecastOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    investigation_api_invoice__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_artifact_api_invoice__invoice_id__artifact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_draft_api_invoice__invoice_id__draft_get: {
        parameters: {
            query?: {
                channel?: components["schemas"]["DraftChannel"];
            };
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_summary_api_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sync_status_api_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"] | null;
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_sync_api_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
